name: cv_build

on:
  push:
    branches:
      - "main"
      - "feature/initial-cv"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: cv.pdf

      - name: Release CV
        uses: softprops/action-gh-release@v1
        with:
          files: cv.pdf
          tag_name: latest